version: '3.0'

services:
  industria1-doctrine-web:
    container_name: industria1-doctrine-web
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - 1000:80
    volumes:
      - ./public:/appdata/www/public
    depends_on:
      - industria1-doctrine-be
    networks:
      - industria1-doctrine-network

  industria1-doctrine-be:
    container_name: industria1-doctrine-be
    build:
      context: docker/php
      args:
        UID: $U_ID
    volumes:
      - ./:/appdata/www
    ###> XDEBUG 3 ###
    # Use your client IP here
    # Linux: run "ip a | grep docker0"
    # Windows (with WSL2) and Mac: host.docker.internal
    environment:
      XDEBUG_CLIENT_HOST: 172.17.0.1
      XDEBUG_CLIENT_PORT: 9005
      PHP_IDE_CONFIG: serverName=industria-doctrine
    networks:
      - industria1-doctrine-network

  industria1-doctrine-db:
    container_name: industria1-doctrine-db
    image: mysql:8.0
    ports:
      - 10000:3306
    environment:
      MYSQL_DATABASE: industria1
      MYSQL_USER: user
      MYSQL_PASSWORD: industria1
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - industria1-doctrine-db-data:/var/lib/mysql
    networks:
      - industria1-doctrine-network
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: industria1-doctrine-db
    depends_on:
      - industria1-doctrine-db
    networks:
      - industria1-doctrine-network
  


###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:

###< doctrine/doctrine-bundle ###

###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
  industria1-doctrine-db-data:

networks:
  industria1-doctrine-network:
    external: true  